---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repo cache (RHEL)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add shh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL44/y3BgQrrz8PA+4WZ7udegp3JROHxzdrLm33yXhlc ansible"


##################################################################################

- hosts: work_stations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    #Don't feel like fumbling around with the link       
        #- name: install terraform
        # unarchive:
        #  src: https://releases.hashicorp.com/terraform/1.14.7/terraform_1.14.7_linux_arm64.zip
        #dest: /usr/local/bin
        #owner: root
        #group: root

##################################################################################

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php on Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php on RHEL9 OS
    tags: apache,rhel,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start httpd (RHEL)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: hange e-mail address for admin
    tags: apache, centos, httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
        # '^' symbol lets ansible know that you want to replace a whole line. Quote has to be at the beginning of the line.  
      regexp: '^Server Admin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "RedHat"
    # tracks the state of httpd
    register: httpd

  - name: restart httpd (RHEL)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    # pulls from the register settting above
    when: httpd.changed


  - name: copy default html file for site
    tags: apache,apache2,http
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

##################################################################################

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb pacakge (RHEL)
    tags: rhel,db,mariadb
    dnf :
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadv-server
      state: latest
    when: ansible_distribution == "Ubuntu"

##################################################################################

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
